using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ToolLib.Cmd
{
    public class AndroidKey
    {
        public const int KEYCODE_UNKNOWN = 0;
        public const int KEYCODE_MENU = 1;
        public const int KEYCODE_SOFT_RIGHT = 2;
        public const int KEYCODE_HOME = 3;
        public const int KEYCODE_BACK = 4;
        public const int KEYCODE_CALL = 5;
        public const int KEYCODE_ENDCALL = 6;
        public const int KEYCODE_0 = 7;
        public const int KEYCODE_1 = 8;
        public const int KEYCODE_2 = 9;
        public const int KEYCODE_3 = 10;
        public const int KEYCODE_4 = 11;
        public const int KEYCODE_5 = 12;
        public const int KEYCODE_6 = 13;
        public const int KEYCODE_7 = 14;
        public const int KEYCODE_8 = 15;
        public const int KEYCODE_9 = 16;
        public const int KEYCODE_STAR = 17;
        public const int KEYCODE_POUND = 18;
        public const int KEYCODE_DPAD_UP = 19;
        public const int KEYCODE_DPAD_DOWN = 20;
        public const int KEYCODE_DPAD_LEFT = 21;
        public const int KEYCODE_DPAD_RIGHT = 22;
        public const int KEYCODE_DPAD_CENTER = 23;
        public const int KEYCODE_VOLUME_UP = 24;
        public const int KEYCODE_VOLUME_DOWN = 25;
        public const int KEYCODE_POWER = 26;
        public const int KEYCODE_CAMERA = 27;
        public const int KEYCODE_CLEAR = 28;
        public const int KEYCODE_A = 29;
        public const int KEYCODE_B = 30;
        public const int KEYCODE_C = 31;
        public const int KEYCODE_D = 32;
        public const int KEYCODE_E = 33;
        public const int KEYCODE_F = 34;
        public const int KEYCODE_G = 35;
        public const int KEYCODE_H = 36;
        public const int KEYCODE_I = 37;
        public const int KEYCODE_J = 38;
        public const int KEYCODE_K = 39;
        public const int KEYCODE_L = 40;
        public const int KEYCODE_M = 41;
        public const int KEYCODE_N = 42;
        public const int KEYCODE_O = 43;
        public const int KEYCODE_P = 44;
        public const int KEYCODE_Q = 45;
        public const int KEYCODE_R = 46;
        public const int KEYCODE_S = 47;
        public const int KEYCODE_T = 48;
        public const int KEYCODE_U = 49;
        public const int KEYCODE_V = 50;
        public const int KEYCODE_W = 51;
        public const int KEYCODE_X = 52;
        public const int KEYCODE_Y = 53;
        public const int KEYCODE_Z = 54;
        public const int KEYCODE_COMMA = 55;
        public const int KEYCODE_PERIOD = 56;
        public const int KEYCODE_ALT_LEFT = 57;
        public const int KEYCODE_ALT_RIGHT = 58;
        public const int KEYCODE_SHIFT_LEFT = 59;
        public const int KEYCODE_SHIFT_RIGHT = 60;
        public const int KEYCODE_TAB = 61;
        public const int KEYCODE_SPACE = 62;
        public const int KEYCODE_SYM = 63;
        public const int KEYCODE_EXPLORER = 64;
        public const int KEYCODE_ENVELOPE = 65;
        public const int KEYCODE_ENTER = 66;
        public const int KEYCODE_DEL = 67;
        public const int KEYCODE_GRAVE = 68;
        public const int KEYCODE_MINUS = 69;
        public const int KEYCODE_EQUALS = 70;
        public const int KEYCODE_LEFT_BRACKET = 71;
        public const int KEYCODE_RIGHT_BRACKET = 72;
        public const int KEYCODE_BACKSLASH = 73;
        public const int KEYCODE_SEMICOLON = 74;
        public const int KEYCODE_APOSTROPHE = 75;
        public const int KEYCODE_SLASH = 76;
        public const int KEYCODE_AT = 77;
        public const int KEYCODE_NUM = 78;
        public const int KEYCODE_HEADSETHOOK = 79;
        public const int KEYCODE_FOCUS = 80;
        public const int KEYCODE_PLUS = 81;
        public const int KEYCODE_MENU_2 = 82;
        public const int KEYCODE_NOTIFICATION = 83;
        public const int KEYCODE_SEARCH = 84;
        public const int TAG_LAST_KEYCODE = 85;
        public const int KEYCODE_ESCAPE = 111;

        //adb shell input keyevent 66.
    }
}
